version: '3'
services:

    resources:
        build: .
        depends_on:
            - postgis
        command: bash -c "./manage.py wait_for_db 2> /dev/null &&
                          ./manage.py makemigrations &&
                          ./manage.py migrate &&
                          ./manage.py runserver 0.0.0.0:8000"
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - POSTGRES_NAME=resources
            - POSTGRES_USER=resources
            - POSTGRES_PASSWORD=Pa55w0rD
            - POSTGRES_HOST=postgis
            - POSTGRES_PORT=5432
        ports:
            - 8080:8000
        volumes:
            - ./:/app
        working_dir: /app
        restart: unless-stopped

    postgis:
        image: kartoza/postgis:latest
        environment:
            - POSTGRES_DBNAME=resources
            - POSTGRES_USER=resources
            - POSTGRES_PASS=Pa55w0rD
            - ALLOW_IP_RANGE=0.0.0.0/0
            #- PGDATA=/var/lib/postgresql/data
        volumes:
            #- ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
            - ./volumes/db/var/lib/postgres_data:/var/lib/postgresql
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
